version: '3.8'
services:
vote:
  image: roxsross12/voting-app:vote-1.0.0
  container_name: vote-app
  ports:
   - 5000:80
  depends_on:
   - redis
  networks:
   - frontend 
   - backend

result:
  image: roxsross12/voting-app:result-1.0.0
  container_name: result-app
  ports:
   - 5001:80
  depends_on:
  - bd
  networks:
  - frontend
  - backend


worker:
  image: roxsross12/voting-app:worker-1.0.0
  container_name: worker-app
  depends_on:
  - bd
  - redis
  networks:
  - backend


bd:
  image: postgres:15-alphine
  container_name: db
  enviroment:
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres
  volumes:
  - db-data:/var/lib/postgresql/data
  networks:
  - backend

redis:
  image: redis:alphine
  container_name: redis
  volumes:
  - redis-data:/data
  networks:
  - backend

volumes:
  db-data:
  redis-data:

networks:
  frontend:
  backend:

